version: "3.5"

services:
  #Elasticsearch service provides a distributed and scalable search service 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    container_name: elasticsearch
    hostname: elasticsearch    
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "http://localhost:9200"]
      interval: 30s
      timeout: 15s
      retries: 15        
#    volumes:
#      - esdata1:/usr/share/elasticsearch/data      
    ports:
      - 9200:9200
      - 9300:9300      
    networks:
      - backend-network 

  #Zookeeper service provides distributed configuration management to Kafka
  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper 
    hostname: zookeeper
    networks:
      - backend-network
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./target/zk-single-kafka-single/zoo1/data:/data
      - ./target/zk-single-kafka-single/zoo1/datalog:/datalog

  #Kafka is the messaging backbone of the micro-service architecture. The objective is avoid point 2 point connections.
  kafka:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka 
    hostname: kafka
    networks:
      - backend-network    
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - ./target/zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  category-database:
    image: postgres:10
    container_name: category-database
    hostname: category-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: ctgry
      POSTGRES_PASSWORD: ctgry
      POSTGRES_DB: category
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ctgry", "-d", "category"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-ctgry:/var/lib/postgresql/data
    restart: on-failure
    stdin_open: true
    tty: true

  ad-database:
    image: postgres:10
    container_name: ad-database
    hostname: ad-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: ad
      POSTGRES_PASSWORD: ad
      POSTGRES_DB: ad
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ad", "-d", "ad"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-ad:/var/lib/postgresql/data
    restart: on-failure
    stdin_open: true
    tty: true

  user-database:
    image: postgres:10
    container_name: user-database
    hostname: user-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: usr
      POSTGRES_DB: user
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "usr", "-d", "user"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-usr:/var/lib/postgresql/data
    restart: on-failure
    stdin_open: true
    tty: true

  image-database:
    image: postgres:10
    container_name: image-database
    hostname: image-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: img
      POSTGRES_PASSWORD: img
      POSTGRES_DB: image
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "img", "-d", "image"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-img:/var/lib/postgresql/data
    restart: on-failure
    stdin_open: true
    tty: true

  #Ad service
  ad-service:
    container_name: ad-service    
    image: corentinbt/ad-service:latest
    hostname: ad-service
    networks:
      - backend-network    
    ports:
      - "15080:8080"
    environment:
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_ADDS_CONNECTION_DASH_URL: "jdbc:postgresql://ad-database:5432/ad"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_ADDS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_ADDS_USER_DASH_NAME: 'ad'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_ADDS_PASSWORD: 'ad'
    depends_on:
      - kafka
      - ad-database

  #Search service
  search-service:
    container_name: search-service    
    image: corentinbt/search-service:latest
    hostname: search-service
    networks:
      - backend-network    
    ports:
      - "11080:8080"
    environment:
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"      
    depends_on:
       - kafka
       - elasticsearch

  #Category service
  category-service:
    container_name: category-service    
    image: corentinbt/category-service:latest
    hostname: category-service
    networks:
      - backend-network    
    ports:
      - "12080:8080"
    environment:
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_CATEGORYDS_CONNECTION_DASH_URL: "jdbc:postgresql://category-database:5432/category"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_CATEGORYDS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_CATEGORYDS_USER_DASH_NAME: 'ctgry'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_CATEGORYDS_PASSWORD: 'ctgry'
    depends_on:
      - kafka
      - category-database
      
  #User service
  user-service:
    container_name: user-service    
    image: corentinbt/user-service:latest
    hostname: user-service
    networks:
      - backend-network    
    ports:
      - "13080:8080"
    environment:
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_USERDS_CONNECTION_DASH_URL: "jdbc:postgresql://user-database:5432/user"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_USERDS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_USERDS_USER_DASH_NAME: 'usr'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_USERDS_PASSWORD: 'usr'
    depends_on:
      - kafka
      - user-database

  #Image service
  image-service:
    container_name: image-service    
    image: corentinbt/image-service:latest
    hostname: image-service
    networks:
      - backend-network    
    ports:
      - "14080:8080"
    environment:
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_IMAGEDS_CONNECTION_DASH_URL: "jdbc:postgresql://image-database:5432/image"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_IMAGEDS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_IMAGEDS_USER_DASH_NAME: 'img'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_IMAGEDS_PASSWORD: 'img'
    depends_on:
      - image-database

volumes:
    pgdata-ctgry:
    pgdata-ad:
    pgdata-usr:
    pgdata-img:
    
volumes:
  esdata1:
    driver: local

networks:
  backend-network:
    driver: bridge
